[package]
name = "ate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termwiz = "0.17.1"
unicode-segmentation = "1.9.0"
